dist: xenial

language: java

cache:
  directories:

  - $HOME/.m2

git:
  depth: false
  quiet: true

env:
  - DATABASE_USERNAME=root DATABASE_PASSWORD= DATABASE_DIALECT=org.hibernate.dialect.MySQL5Dialect

before_install:
- echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
- git lfs pull


script:
- bundle exec mvn package 

services:
  - mysql
  
